#!/usr/bin/env python3
"""Create the three R1 ODT fixtures with the system LibreOffice over UNO."""

from __future__ import annotations

import argparse
import shutil
import socket
import subprocess
import tempfile
import time
from pathlib import Path

import uno


PARAGRAPH_BREAK = uno.getConstantByName(
    "com.sun.star.text.ControlCharacter.PARAGRAPH_BREAK"
)
BREAK_NONE = uno.Enum("com.sun.star.style.BreakType", "NONE")
BREAK_PAGE_BEFORE = uno.Enum("com.sun.star.style.BreakType", "PAGE_BEFORE")
AS_CHARACTER = uno.Enum("com.sun.star.text.TextContentAnchorType", "AS_CHARACTER")


def property_value(name: str, value: object):
    prop = uno.createUnoStruct("com.sun.star.beans.PropertyValue")
    prop.Name = name
    prop.Value = value
    return prop


def file_url(path: Path) -> str:
    return uno.systemPathToFileUrl(str(path.resolve()))


def free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def connect(port: int, attempts: int = 80):
    local_context = uno.getComponentContext()
    resolver = local_context.ServiceManager.createInstanceWithContext(
        "com.sun.star.bridge.UnoUrlResolver", local_context
    )
    url = (
        f"uno:socket,host=127.0.0.1,port={port};"
        "urp;StarOffice.ComponentContext"
    )
    for _ in range(attempts):
        try:
            return resolver.resolve(url)
        except Exception:
            time.sleep(0.25)
    raise RuntimeError(f"unable to connect to LibreOffice on port {port}")


def new_writer(desktop):
    hidden = (property_value("Hidden", True),)
    return desktop.loadComponentFromURL("private:factory/swriter", "_blank", 0, hidden)


def add_paragraph(doc, content: str, style: str | None = None,
                  page_break_before: bool = False):
    text = doc.Text
    cursor = text.createTextCursorByRange(text.End)
    cursor.BreakType = BREAK_PAGE_BEFORE if page_break_before else BREAK_NONE
    if style:
        cursor.ParaStyleName = style
    text.insertString(cursor, content, False)
    text.insertControlCharacter(cursor, PARAGRAPH_BREAK, False)
    return cursor


def store_odt(doc, path: Path, office_version: str) -> int:
    properties = doc.DocumentProperties
    properties.Subject = "wasm_sdk_probe R1 fixture"
    properties.Description = f"Generated by {office_version} via UNO"
    doc.storeAsURL(
        file_url(path),
        (
            property_value("FilterName", "writer8"),
            property_value("Overwrite", True),
        ),
    )
    try:
        page_count = int(doc.CurrentController.PageCount)
    except Exception:
        page_count = -1
    doc.close(True)
    return page_count


def make_plain(desktop, output: Path, office_version: str) -> int:
    doc = new_writer(desktop)
    doc.DocumentProperties.Title = "R1 純文字中英混排測試"
    add_paragraph(doc, "R1 純文字中英混排測試", "Title")
    content = (
        "這是一份用來驗證 LibreOfficeKit WebAssembly 文件流程的測試文件。"
        "內容包含繁體中文、English words、數字 1234567890，以及全形標點：「」，。！？；：。"
        "測試時，JavaScript 會把這份文件寫入 MEMFS，再由 headless Writer 開啟。"
        "接著使用 paintTile 繪製頁面、在游標位置插入中文字『測』，最後另存為新的 ODT。"
        "我們需要確認字型顯示正常、段落沒有遺失、輸出的壓縮封裝與 content.xml 都能解析。"
        "若流程可以在不同瀏覽器連續重跑，就代表最小文件 SDK 的技術切片成立。"
        "本段也加入常用字：天地玄黃、日月山川、春夏秋冬、東西南北、臺灣軟體工程。"
    )
    add_paragraph(doc, content)
    add_paragraph(doc, "Final line：ODT round-trip 完整性檢查。")
    return store_odt(doc, output, office_version)


def make_styled(desktop, output: Path, image_path: Path,
                office_version: str) -> int:
    doc = new_writer(desktop)
    doc.DocumentProperties.Title = "R1 樣式、表格、圖片與註解測試"
    add_paragraph(doc, "R1 樣式文件", "Title")
    add_paragraph(doc, "第一節：標題與內文", "Heading 1")
    add_paragraph(
        doc,
        "這一頁使用標題樣式與一般內文，測試 round-trip 後樣式關聯是否仍然存在。"
        "段落同時包含中文與 English。",
    )

    text = doc.Text
    table_cursor = text.createTextCursorByRange(text.End)
    table = doc.createInstance("com.sun.star.text.TextTable")
    table.initialize(3, 3)
    text.insertTextContent(table_cursor, table, False)
    values = {
        "A1": "項目", "B1": "值", "C1": "備註",
        "A2": "渲染", "B2": "512×512", "C2": "RGBA tile",
        "A3": "輸入", "B3": "測", "C3": "UTF-8 paste",
    }
    for cell_name, value in values.items():
        cell = table.getCellByName(cell_name)
        cell.String = value
        if cell_name.endswith("1"):
            cell.BackColor = 0xD9EAF7

    add_paragraph(doc, "第二節：嵌入圖片", "Heading 1", page_break_before=True)
    add_paragraph(doc, "下方圖片由測試專案內的 PNG 載入並嵌入 ODT 封裝。")
    graphic_object = doc.createInstance("com.sun.star.text.TextGraphicObject")
    graphic_object.GraphicURL = file_url(image_path)
    graphic_object.AnchorType = AS_CHARACTER
    graphic_object.Width = 12000
    graphic_object.Height = 6750
    image_cursor = text.createTextCursorByRange(text.End)
    text.insertTextContent(image_cursor, graphic_object, False)
    text.insertControlCharacter(image_cursor, PARAGRAPH_BREAK, False)

    add_paragraph(doc, "第三節：註解", "Heading 1", page_break_before=True)
    comment_cursor = text.createTextCursorByRange(text.End)
    text.insertString(comment_cursor, "這句話具有一則測試註解。", False)
    annotation = doc.createInstance("com.sun.star.text.textfield.Annotation")
    annotation.Author = "wasm_sdk_probe"
    annotation.Content = "R1 round-trip 必須保留這則註解。"
    text.insertTextContent(comment_cursor, annotation, False)
    text.insertControlCharacter(comment_cursor, PARAGRAPH_BREAK, False)
    add_paragraph(doc, "文件結尾：請確認表格、圖片、註解與標題樣式均保留。")
    return store_odt(doc, output, office_version)


def make_long(desktop, output: Path, office_version: str) -> int:
    doc = new_writer(desktop)
    doc.DocumentProperties.Title = "R1 20 頁以上長文件測試"
    body = (
        "WebAssembly 文件引擎需要在有限的瀏覽器記憶體中穩定處理長篇內容。"
        "這一頁反覆使用繁體中文文字，觀察開檔、首次繪製與儲存所需時間。"
        "每個段落都包含標點、數字 0123456789，以及 English compatibility text。"
        "量測重點是相對規模效應，不以本文件模擬真實排版品質基準。"
    )
    for page in range(1, 23):
        add_paragraph(
            doc,
            f"第 {page} 頁：長文件記憶體與效能測試",
            "Heading 1",
            page_break_before=page > 1,
        )
        for paragraph in range(1, 6):
            add_paragraph(doc, f"段落 {paragraph}。{body}{body}")
    return store_odt(doc, output, office_version)


def main() -> None:
    parser = argparse.ArgumentParser()
    project = Path(__file__).resolve().parent.parent
    parser.add_argument("--output", type=Path, default=project / "test-docs")
    parser.add_argument("--soffice", default=shutil.which("soffice") or "soffice")
    parser.add_argument("--only", choices=("all", "t1", "t2", "t3"), default="all")
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    office_version = subprocess.run(
        [args.soffice, "--version"], check=True, capture_output=True, text=True
    ).stdout.strip()
    port = free_port()

    with tempfile.TemporaryDirectory(prefix="wasm-sdk-probe-lo-") as profile:
        accept = f"socket,host=127.0.0.1,port={port};urp;StarOffice.ServiceManager"
        process = subprocess.Popen(
            [
                args.soffice,
                "--headless",
                "--nologo",
                "--nodefault",
                "--nofirststartwizard",
                "--norestore",
                f"-env:UserInstallation={file_url(Path(profile))}",
                f"--accept={accept}",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        try:
            context = connect(port)
            desktop = context.ServiceManager.createInstanceWithContext(
                "com.sun.star.frame.Desktop", context
            )
            makers = {
                "t1": ("t1-plain-zh.odt", lambda: make_plain(
                    desktop, args.output / "t1-plain-zh.odt", office_version
                )),
                "t2": ("t2-styled.odt", lambda: make_styled(
                    desktop,
                    args.output / "t2-styled.odt",
                    project / "assets" / "r1-test-image.png",
                    office_version,
                )),
                "t3": ("t3-long.odt", lambda: make_long(
                    desktop, args.output / "t3-long.odt", office_version
                )),
            }
            selected = makers if args.only == "all" else {args.only: makers[args.only]}
            results = {name: make() for name, make in selected.values()}
            desktop.terminate()
        finally:
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.terminate()
                process.wait(timeout=10)

    print(office_version)
    for name, pages in results.items():
        print(f"{name}: {pages} pages")


if __name__ == "__main__":
    main()
